// apps/gm-desktop/src/lib/components/Sidebar.svelte
<!--
  Sidebar nav. svelte-spa-router drives routing via `href` (the
  hash form is `/path`). The active link is computed by
  `location` + a per-link prefix check (so `/repos/foo` keeps
  "Repositories" highlighted).
-->
<script lang="ts">
  import { location } from 'svelte-spa-router';
  import { t } from '$lib/i18n';
  import { derived } from 'svelte/store';
  import ThemeToggle from './ThemeToggle.svelte';
  import LocaleSwitcher from './LocaleSwitcher.svelte';

  type NavItem = { href: string; labelKey: string; icon: string };

  const items: NavItem[] = [
    { href: '/', labelKey: 'nav.dashboard', icon: '🏠' },
    { href: '/repos', labelKey: 'nav.repos', icon: '📦' },
    { href: '/vault', labelKey: 'nav.vault', icon: '🔐' },
    { href: '/settings', labelKey: 'nav.settings', icon: '⚙️' },
  ];

  const activePath = derived(location, ($loc) => $loc);

  function isActive(item: NavItem, current: string): boolean {
    if (item.href === '/') return current === '/';
    return current === item.href || current.startsWith(item.href + '/');
  }
</script>

<aside
  class="flex h-full w-56 shrink-0 flex-col border-r border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-800"
  data-testid="sidebar"
>
  <div class="flex items-center gap-2 px-4 py-4 text-base font-semibold">
    <span class="text-xl">🌿</span>
    <span>{$t('common.appName')}</span>
  </div>

  <nav class="flex-1 space-y-1 px-2" aria-label="primary">
    {#each items as item (item.href)}
      {@const active = isActive(item, $activePath)}
      <a
        href={item.href}
        class="block rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-slate-100 dark:hover:bg-slate-700"
        class:bg-accent-50={active}
        class:text-accent-700={active}
        class:dark:bg-slate-700={active}
        class:dark:text-white={active}
        aria-current={active ? 'page' : undefined}
        data-testid={`nav-${item.labelKey}`}
      >
        <span class="mr-2">{item.icon}</span>
        <span>{$t(item.labelKey)}</span>
      </a>
    {/each}
  </nav>

  <div class="border-t border-slate-200 p-3 space-y-2 dark:border-slate-700">
    <ThemeToggle />
    <LocaleSwitcher />
  </div>
</aside>

// apps/gm-console/src/components/Sidebar.tsx
import { NavLink, useLocation } from 'react-router-dom';
import clsx from 'clsx';
import { useTranslate } from '@/i18n/runtime';
import { LocaleSwitcher } from './LocaleSwitcher';
import { ThemeToggle } from './ThemeToggle';

interface NavItem {
  to: string;
  labelKey: string;
  match: (pathname: string) => boolean;
}

const NAV_ITEMS: ReadonlyArray<NavItem> = [
  { to: '/', labelKey: 'app.nav.repos', match: (p) => p === '/' || p.startsWith('/repos') },
  { to: '/vault', labelKey: 'app.nav.vault', match: (p) => p.startsWith('/vault') },
  { to: '/settings', labelKey: 'app.nav.settings', match: (p) => p.startsWith('/settings') },
];

interface SidebarProps {
  open: boolean;
  onClose: () => void;
}

/**
 * Two-pane shell. On mobile, the sidebar slides in as a drawer
 * (`open` prop); on `md:` it becomes a persistent column.
 */
export function Sidebar({ open, onClose }: SidebarProps) {
  const t = useTranslate();
  const { pathname } = useLocation();
  return (
    <>
      {/* Mobile backdrop */}
      <div
        aria-hidden="true"
        onClick={onClose}
        className={
          'fixed inset-0 z-30 bg-slate-900/50 transition-opacity md:hidden ' +
          (open ? 'opacity-100' : 'pointer-events-none opacity-0')
        }
      />
      <aside
        aria-label="Primary"
        className={clsx(
          'fixed inset-y-0 left-0 z-40 flex w-64 flex-col border-r border-slate-200 bg-white p-4 transition-transform md:static md:translate-x-0 dark:border-slate-800 dark:bg-slate-950',
          open ? 'translate-x-0' : '-translate-x-full md:translate-x-0',
        )}
      >
        <header className="mb-6 flex flex-col gap-1">
          <span className="text-lg font-semibold tracking-tight text-brand-600 dark:text-brand-400">
            {t('app.title')}
          </span>
          <span className="text-xs text-slate-500 dark:text-slate-400">{t('app.subtitle')}</span>
        </header>
        <nav aria-label="Sections" className="flex-1 space-y-1">
          {NAV_ITEMS.map((item) => {
            const active = item.match(pathname);
            return (
              <NavLink
                key={item.to}
                to={item.to}
                end={item.to === '/'}
                onClick={onClose}
                aria-current={active ? 'page' : undefined}
                className={clsx(
                  'block rounded-md px-3 py-2 text-sm font-medium transition',
                  active
                    ? 'bg-brand-50 text-brand-700 dark:bg-brand-900/30 dark:text-brand-200'
                    : 'text-slate-700 hover:bg-slate-100 dark:text-slate-200 dark:hover:bg-slate-800',
                )}
              >
                {t(item.labelKey)}
              </NavLink>
            );
          })}
        </nav>
        <footer className="mt-4 flex items-center justify-between gap-2 border-t border-slate-200 pt-4 dark:border-slate-800">
          <LocaleSwitcher />
          <ThemeToggle />
        </footer>
      </aside>
    </>
  );
}
