// apps/gm-desktop/src/lib/components/ThemeToggle.svelte
<!--
  ThemeToggle. Three-button segmented control bound to the
  `theme` store.
-->
<script lang="ts">
  import { theme, setTheme, type ThemeMode } from '$lib/stores/theme';
  import { t } from '$lib/i18n';

  const modes: ReadonlyArray<{ id: ThemeMode; labelKey: string }> = [
    { id: 'light', labelKey: 'settings.themeLight' },
    { id: 'auto', labelKey: 'settings.themeAuto' },
    { id: 'dark', labelKey: 'settings.themeDark' },
  ];
</script>

<fieldset class="flex items-center gap-1" data-testid="theme-toggle">
  <legend class="sr-only">{$t('settings.theme')}</legend>
  {#each modes as mode (mode.id)}
    <button
      type="button"
      class="rounded-md px-2 py-1 text-xs font-medium transition-colors"
      class:bg-accent-500={$theme === mode.id}
      class:text-white={$theme === mode.id}
      class:bg-slate-200={$theme !== mode.id}
      class:dark:bg-slate-700={$theme !== mode.id}
      class:hover:bg-slate-300={$theme !== mode.id}
      class:dark:hover:bg-slate-600={$theme !== mode.id}
      onclick={() => setTheme(mode.id)}
      aria-pressed={$theme === mode.id}
      data-testid={`theme-${mode.id}`}
    >
      {$t(mode.labelKey)}
    </button>
  {/each}
</fieldset>

// apps/gm-console/src/components/ThemeToggle.tsx
import { useThemeStore, type Theme } from '@/stores/theme';

const OPTIONS: ReadonlyArray<{ value: Theme; label: string }> = [
  { value: 'light', label: '☀' },
  { value: 'system', label: '◐' },
  { value: 'dark', label: '☾' },
];

/**
 * Three-way theme toggle. Compact, icon-only, accessible (radiogroup).
 * Persists to localStorage via the store.
 */
export function ThemeToggle() {
  const theme = useThemeStore((s) => s.theme);
  const setTheme = useThemeStore((s) => s.setTheme);
  return (
    <div
      role="radiogroup"
      aria-label="Theme"
      className="inline-flex overflow-hidden rounded-md border border-slate-300 bg-white text-sm dark:border-slate-700 dark:bg-slate-900"
    >
      {OPTIONS.map((opt) => (
        <button
          key={opt.value}
          type="button"
          role="radio"
          aria-checked={theme === opt.value}
          aria-label={`Theme: ${opt.value}`}
          onClick={() => setTheme(opt.value)}
          className={
            'px-2.5 py-1.5 transition ' +
            (theme === opt.value
              ? 'bg-brand-600 text-white'
              : 'text-slate-700 hover:bg-slate-100 dark:text-slate-200 dark:hover:bg-slate-800')
          }
        >
          <span aria-hidden="true">{opt.label}</span>
        </button>
      ))}
    </div>
  );
}
